### ISSUE TITLE
Questions about dataset

### ISSUE THREAD

**Issue by ShangWangCS** [dominiktraxl/artracks#1]
Has the data set you calculated been used for the publication of the article? Is the result of your data correct and can it be used directly?

**Comment by dominiktraxl** [comment]
Yes, the data has been used for this publication: https://doi.org/10.5194/hess-27-2645-2023

In terms of the quality of the data, please read the "About" section of this repository: https://github.com/dominiktraxl/artracks#about. Considering the caveats stated there, the data can be used directly.
